#!/usr/bin/env python
# -*- coding: utf-8 -*-

# CAVEAT UTILITOR
#
# This file was automatically generated by Grako.
#
#    https://pypi.python.org/pypi/grako/
#
# Any changes you make to it will be overwritten the next time
# the file is generated.


from __future__ import print_function, division, absolute_import, unicode_literals

from grako.parsing import graken, Parser
from grako.util import re, RE_FLAGS, generic_main  # noqa


__version__ = (2016, 4, 5, 18, 42, 21, 1)

__all__ = [
    'SSSLParser',
    'SSSLSemantics',
    'main'
]

KEYWORDS = set([])


class SSSLParser(Parser):
    def __init__(self,
                 whitespace=None,
                 nameguard=None,
                 comments_re=None,
                 eol_comments_re=None,
                 ignorecase=None,
                 left_recursion=True,
                 keywords=KEYWORDS,
                 **kwargs):
        super(SSSLParser, self).__init__(
            whitespace=whitespace,
            nameguard=nameguard,
            comments_re=comments_re,
            eol_comments_re=eol_comments_re,
            ignorecase=ignorecase,
            left_recursion=left_recursion,
            keywords=keywords,
            **kwargs
        )

    @graken()
    def _START_(self):

        def block0():
            self._DEFS_()
            self.add_last_node_to_name('BLOCK')
        self._closure(block0)
        self._check_eof()

        self.ast._define(
            [],
            ['BLOCK']
        )

    @graken()
    def _DEFS_(self):
        with self._choice():
            with self._option():
                self._DOBJT_()
                self.name_last_node('DOBJT')
            with self._option():
                self._DMAIN_()
                self.name_last_node('DMAIN')
            with self._option():
                self._DFUNC_()
                self.name_last_node('DFUNC')
            with self._option():
                self._DECLAFF_()
                self.name_last_node('DECLAFF')
            with self._option():
                self._DECLAFF_()
                self.name_last_node('DECLAFF')
            with self._option():
                self._DECL_()
                self.name_last_node('DECL')
            self._error('no available options')

        self.ast._define(
            ['DOBJT', 'DMAIN', 'DFUNC', 'DECLAFF', 'DECL'],
            []
        )

    @graken()
    def _BLOCK_(self):
        with self._choice():
            with self._option():
                self._token('{')
                self._EMPTY_()
                self.name_last_node('@')
                self._token('}')
            with self._option():
                self._token('{')
                with self._group():
                    with self._choice():
                        with self._option():

                            def block1():
                                self._INSTR_()
                                self.add_last_node_to_name('@')
                            self._positive_closure(block1)
                        with self._option():
                            self._NULL_()
                            self.name_last_node('@')
                        self._error('no available options')
                self._token('}')
            self._error('no available options')

    @graken()
    def _INSTR_(self):
        with self._choice():
            with self._option():
                self._COND_()
                self.name_last_node('@')
            with self._option():
                self._OTHER_()
                self.name_last_node('@')
                self._token(';')
            with self._option():
                self._CFUNC_()
                self.name_last_node('CFUNC')
                self._token(';')
            with self._option():
                self._DEFS_()
                self.name_last_node('@')
            with self._option():
                self._AFF_()
                self.name_last_node('AFF')
            self._error('no available options')

        self.ast._define(
            ['CFUNC', 'AFF'],
            []
        )

    @graken()
    def _COND_(self):
        with self._choice():
            with self._option():
                self._IF_()
                self.name_last_node('IF')
            with self._option():
                self._ELSE_()
                self.name_last_node('ELSE')
            with self._option():
                self._ELIF_()
                self.name_last_node('ELIF')
            with self._option():
                self._WHILE_()
                self.name_last_node('WHILE')
            with self._option():
                self._DOWHILE_()
                self.name_last_node('DOWHILE')
            self._error('no available options')

        self.ast._define(
            ['IF', 'ELSE', 'ELIF', 'WHILE', 'DOWHILE'],
            []
        )

    @graken()
    def _DECL_(self):
        self._TYPE_()
        self.name_last_node('TYPE')
        self._nom_()
        self.name_last_node('NAME')
        self._token(';')

        self.ast._define(
            ['TYPE', 'NAME'],
            []
        )

    @graken()
    def _DECLAFF_(self):
        self._TYPE_()
        self.name_last_node('TYPE')
        self._nom_()
        self.name_last_node('NAME')
        self._token('=')
        self._EXPR_()
        self.name_last_node('EXPR')
        self._token(';')

        self.ast._define(
            ['TYPE', 'NAME', 'EXPR'],
            []
        )

    @graken()
    def _AFF_(self):
        self._nom_()
        self.name_last_node('NAME')
        self._token('=')
        self._EXPR_()
        self.name_last_node('EXPR')
        self._token(';')

        self.ast._define(
            ['NAME', 'EXPR'],
            []
        )

    @graken()
    def _CFUNC_(self):
        self._nom_()
        self.name_last_node('NAME')
        self._ARGS_()
        self.name_last_node('ARGS')

        self.ast._define(
            ['NAME', 'ARGS'],
            []
        )

    @graken()
    def _OTHER_(self):
        with self._choice():
            with self._option():
                self._RETURN_()
                self.name_last_node('RETURN')
            with self._option():
                self._BREAK_()
                self.name_last_node('BREAK')
            with self._option():
                self._ECHO_()
                self.name_last_node('ECHO')
            with self._option():
                self._ECHOLN_()
                self.name_last_node('ECHOLN')
            self._error('no available options')

        self.ast._define(
            ['RETURN', 'BREAK', 'ECHO', 'ECHOLN'],
            []
        )

    @graken()
    def _RETURN_(self):
        with self._choice():
            with self._option():
                self._token('return')
                self._token('(')
                self._EXPR_()
                self.name_last_node('EXPR')
                self._token(')')
            with self._option():
                self._token('return')
                self._token('(')
                self._EMPTY_()
                self.name_last_node('@')
                self._token(')')
            self._error('no available options')

        self.ast._define(
            ['EXPR'],
            []
        )

    @graken()
    def _BREAK_(self):
        self._token('break')
        self._EMPTY_()
        self.name_last_node('@')

    @graken()
    def _ECHO_(self):
        self._token('echo')
        self._token('(')
        self._EXPR_()
        self.name_last_node('EXPR')
        self._token(')')

        self.ast._define(
            ['EXPR'],
            []
        )

    @graken()
    def _ECHOLN_(self):
        self._token('echoln')
        self._token('(')
        self._EXPR_()
        self.name_last_node('EXPR')
        self._token(')')

        self.ast._define(
            ['EXPR'],
            []
        )

    @graken()
    def _IF_(self):
        self._token('if')
        self._token('(')
        self._EXPR_()
        self.name_last_node('EXPR')
        self._token(')')
        self._BLOCK_()
        self.name_last_node('BLOCK')

        self.ast._define(
            ['EXPR', 'BLOCK'],
            []
        )

    @graken()
    def _ELSE_(self):
        self._token('else')
        self._BLOCK_()
        self.name_last_node('BLOCK')

        self.ast._define(
            ['BLOCK'],
            []
        )

    @graken()
    def _ELIF_(self):
        self._token('elif')
        self._token('(')
        self._EXPR_()
        self.name_last_node('EXPR')
        self._token(')')
        self._BLOCK_()
        self.name_last_node('BLOCK')

        self.ast._define(
            ['EXPR', 'BLOCK'],
            []
        )

    @graken()
    def _WHILE_(self):
        self._token('while')
        self._token('(')
        self._EXPR_()
        self.name_last_node('EXPR')
        self._token(')')
        self._BLOCK_()
        self.name_last_node('BLOCK')

        self.ast._define(
            ['EXPR', 'BLOCK'],
            []
        )

    @graken()
    def _DOWHILE_(self):
        self._token('do')
        self._BLOCK_()
        self.name_last_node('BLOCK')
        self._token('while')
        self._token('(')
        self._EXPR_()
        self.name_last_node('EXPR')
        self._token(')')

        self.ast._define(
            ['BLOCK', 'EXPR'],
            []
        )

    @graken()
    def _PARAM_(self):
        with self._choice():
            with self._option():
                self._token('(')
                self._EMPTY_()
                self.name_last_node('@')
                self._token(')')
            with self._option():
                self._token('(')
                with self._optional():
                    self.__TYPE_()
                    self.name_last_node('@')
                    self.__nom_()
                    self.name_last_node('@')

                    def block3():
                        self._token(',')
                        self.__TYPE_()
                        self.name_last_node('@')
                        self.__nom_()
                        self.name_last_node('@')
                    self._closure(block3)
                self._token(')')
            self._error('expecting one of: (')

    @graken()
    def _ARGS_(self):
        with self._choice():
            with self._option():
                self._token('(')
                self._EMPTY_()
                self.name_last_node('@')
                self._token(')')
            with self._option():
                self._token('(')
                with self._optional():
                    self.__EXPR_()
                    self.add_last_node_to_name('@')

                    def block2():
                        self._token(',')
                        self.__EXPR_()
                        self.add_last_node_to_name('@')
                    self._closure(block2)
                self._token(')')
            self._error('expecting one of: (')

    @graken()
    def _EMPTY_(self):
        self._empty_closure()

    @graken()
    def _DOBJT_(self):
        self._token('class')
        self._nom_()
        self.name_last_node('NAME')
        self._token('{')

        def block1():
            self._DMEMB_()
            self.add_last_node_to_name('BLOCK')
        self._closure(block1)
        self._token('}')

        self.ast._define(
            ['NAME'],
            ['BLOCK']
        )

    @graken()
    def _DMEMB_(self):
        with self._choice():
            with self._option():
                self._DFUNC_()
                self.name_last_node('CLASSDFUNC')
            with self._option():
                self._DECLAFF_()
                self.name_last_node('DECLAFF')
            with self._option():
                self._DECL_()
                self.name_last_node('CLASSDECL')
            with self._option():
                self._CSTR_()
                self.name_last_node('CSTR')
            self._error('no available options')

        self.ast._define(
            ['CLASSDFUNC', 'DECLAFF', 'CLASSDECL', 'CSTR'],
            []
        )

    @graken()
    def _DFUNC_(self):
        self._token('func')
        self._TYPE_()
        self.name_last_node('TYPE')
        self._nom_()
        self.name_last_node('NAME')
        self._PARAM_()
        self.name_last_node('PARAM')
        self._BLOCK_()
        self.name_last_node('BLOCK')

        self.ast._define(
            ['TYPE', 'NAME', 'PARAM', 'BLOCK'],
            []
        )

    @graken()
    def _DMAIN_(self):
        self._TYPE_()
        self.name_last_node('TYPE')
        self._token('Main')
        self.name_last_node('NAME')
        self._PARAM_()
        self.name_last_node('PARAM')
        self._BLOCK_()
        self.name_last_node('BLOCK')

        self.ast._define(
            ['TYPE', 'NAME', 'PARAM', 'BLOCK'],
            []
        )

    @graken()
    def _CSTR_(self):
        self._nom_()
        self.name_last_node('NAME')
        self._PARAM_()
        self.name_last_node('PARAM')
        self._BLOCK_()
        self.name_last_node('BLOCK')

        self.ast._define(
            ['NAME', 'PARAM', 'BLOCK'],
            []
        )

    @graken()
    def _TYPE_(self):
        with self._choice():
            with self._option():
                self._PTYPE_()
                self.name_last_node('@')
            with self._option():
                self._nom_()
                self.name_last_node('@')
            self._error('no available options')

    @graken()
    def _OPER_(self):
        with self._choice():
            with self._option():
                self._token('.')
            with self._option():
                self._token('+')
            with self._option():
                self._token('-')
            with self._option():
                self._token('*')
            with self._option():
                self._token('/')
            with self._option():
                self._token('==')
            with self._option():
                self._token('!=')
            with self._option():
                self._token('>')
            with self._option():
                self._token('<')
            with self._option():
                self._token('>=')
            with self._option():
                self._token('<=')
            with self._option():
                self._token('or')
            with self._option():
                self._token('and')
            self._error('expecting one of: != * + - . / < <= == > >= and or')

    @graken()
    def _PTYPE_(self):
        with self._choice():
            with self._option():
                self._token('int')
            with self._option():
                self._token('float')
            with self._option():
                self._token('string')
            with self._option():
                self._token('void')
            with self._option():
                self._token('bool')
            self._error('expecting one of: bool float int string void')

    @graken()
    def _KEYW_(self):
        with self._choice():
            with self._option():
                self._PTYPE_()
                self.name_last_node('@')
            with self._option():
                self._token('return')
            with self._option():
                self._token('back')
            with self._option():
                self._token('or')
            with self._option():
                self._token('and')
            with self._option():
                self._token('class')
            with self._option():
                self._token('func')
            with self._option():
                self._token('echo')
            with self._option():
                self._token('echoln')
            with self._option():
                self._token('Main')
            self._error('expecting one of: Main and back class echo echoln func or return')

    @graken()
    def _EXPR_(self):
        self._or_EXPR_()
        self.name_last_node('@')

    @graken()
    def _or_EXPR_(self):
        self._and_EXPR_()
        self.name_last_node('@')

        def block1():
            self._token('or')
            self.name_last_node('@')
            self._and_EXPR_()
            self.name_last_node('@')
        self._closure(block1)

    @graken()
    def _and_EXPR_(self):
        self._e_EXPR_()
        self.name_last_node('@')

        def block1():
            self._token('and')
            self.name_last_node('@')
            self._e_EXPR_()
            self.name_last_node('@')
        self._closure(block1)

    @graken()
    def _e_EXPR_(self):
        self._a_EXPR_()
        self.name_last_node('@')

        def block1():
            with self._group():
                with self._choice():
                    with self._option():
                        self._token('==')
                    with self._option():
                        self._token('!=')
                    with self._option():
                        self._token('>=')
                    with self._option():
                        self._token('<=')
                    with self._option():
                        self._token('>')
                    with self._option():
                        self._token('<')
                    self._error('expecting one of: != < <= == > >=')
            self.name_last_node('@')
            self._a_EXPR_()
            self.name_last_node('@')
        self._closure(block1)

    @graken()
    def _a_EXPR_(self):
        self._m_EXPR_()
        self.name_last_node('@')

        def block1():
            with self._group():
                with self._choice():
                    with self._option():
                        self._token('+')
                    with self._option():
                        self._token('-')
                    self._error('expecting one of: + -')
            self.name_last_node('@')
            self._m_EXPR_()
            self.name_last_node('@')
        self._closure(block1)

    @graken()
    def _m_EXPR_(self):
        self._p_EXPR_()
        self.name_last_node('@')

        def block1():
            with self._group():
                with self._choice():
                    with self._option():
                        self._token('*')
                    with self._option():
                        self._token('/')
                    self._error('expecting one of: * /')
            self.name_last_node('@')
            self._p_EXPR_()
            self.name_last_node('@')
        self._closure(block1)

    @graken()
    def _p_EXPR_(self):
        self._t_EXPR_()
        self.name_last_node('@')

        def block1():
            with self._group():
                self._token('.')
            self.name_last_node('@')
            self._t_EXPR_()
            self.name_last_node('@')
        self._closure(block1)

    @graken()
    def _t_EXPR_(self):
        with self._choice():
            with self._option():
                self._token('(')
                self._EXPR_()
                self.name_last_node('PARENTH')
                self._token(')')
            with self._option():
                self._CFUNC_()
                self.name_last_node('CFUNC')
            with self._option():
                self._nom_()
                self.name_last_node('NAME')
            with self._option():
                self._val_()
                self.name_last_node('VAL')
            self._error('no available options')

        self.ast._define(
            ['PARENTH', 'CFUNC', 'NAME', 'VAL'],
            []
        )

    @graken()
    def _nom_(self):
        with self._ifnot():
            self._KEYW_()
        self._pattern(r'[a-zA-Z_][a-zA-Z0-9_]*')

    @graken()
    def _val_(self):
        with self._choice():
            with self._option():
                self._pattern(r'[0-9]+[.]?[0-9]*')
            with self._option():
                self._pattern(r"['].*[']")
            self._error("expecting one of: ['].*['] [0-9]+[.]?[0-9]*")

    @graken()
    def _NULL_(self):
        pass
        self.name_last_node('@')

    @graken()
    def __DFUNC_(self):
        self._DFUNC_()
        self.name_last_node('DFUNC')

        self.ast._define(
            ['DFUNC'],
            []
        )

    @graken()
    def __DECLAFF_(self):
        self._DECLAFF_()
        self.name_last_node('DECLAFF')

        self.ast._define(
            ['DECLAFF'],
            []
        )

    @graken()
    def __DECL_(self):
        self._DECL_()
        self.name_last_node('DECL')

        self.ast._define(
            ['DECL'],
            []
        )

    @graken()
    def __TYPE_(self):
        self._TYPE_()
        self.name_last_node('TYPE')

        self.ast._define(
            ['TYPE'],
            []
        )

    @graken()
    def __nom_(self):
        self._nom_()
        self.name_last_node('NAME')

        self.ast._define(
            ['NAME'],
            []
        )

    @graken()
    def __CSTR_(self):
        self._CSTR_()
        self.name_last_node('CSTR')

        self.ast._define(
            ['CSTR'],
            []
        )

    @graken()
    def __EXPR_(self):
        self._EXPR_()
        self.name_last_node('EXPR')

        self.ast._define(
            ['EXPR'],
            []
        )


class SSSLSemantics(object):
    def START(self, ast):
        return ast

    def DEFS(self, ast):
        return ast

    def BLOCK(self, ast):
        return ast

    def INSTR(self, ast):
        return ast

    def COND(self, ast):
        return ast

    def DECL(self, ast):
        return ast

    def DECLAFF(self, ast):
        return ast

    def AFF(self, ast):
        return ast

    def CFUNC(self, ast):
        return ast

    def OTHER(self, ast):
        return ast

    def RETURN(self, ast):
        return ast

    def BREAK(self, ast):
        return ast

    def ECHO(self, ast):
        return ast

    def ECHOLN(self, ast):
        return ast

    def IF(self, ast):
        return ast

    def ELSE(self, ast):
        return ast

    def ELIF(self, ast):
        return ast

    def WHILE(self, ast):
        return ast

    def DOWHILE(self, ast):
        return ast

    def PARAM(self, ast):
        return ast

    def ARGS(self, ast):
        return ast

    def EMPTY(self, ast):
        return ast

    def DOBJT(self, ast):
        return ast

    def DMEMB(self, ast):
        return ast

    def DFUNC(self, ast):
        return ast

    def DMAIN(self, ast):
        return ast

    def CSTR(self, ast):
        return ast

    def TYPE(self, ast):
        return ast

    def OPER(self, ast):
        return ast

    def PTYPE(self, ast):
        return ast

    def KEYW(self, ast):
        return ast

    def EXPR(self, ast):
        return ast

    def or_EXPR(self, ast):
        return ast

    def and_EXPR(self, ast):
        return ast

    def e_EXPR(self, ast):
        return ast

    def a_EXPR(self, ast):
        return ast

    def m_EXPR(self, ast):
        return ast

    def p_EXPR(self, ast):
        return ast

    def t_EXPR(self, ast):
        return ast

    def nom(self, ast):
        return ast

    def val(self, ast):
        return ast

    def NULL(self, ast):
        return ast

    def _DFUNC(self, ast):
        return ast

    def _DECLAFF(self, ast):
        return ast

    def _DECL(self, ast):
        return ast

    def _TYPE(self, ast):
        return ast

    def _nom(self, ast):
        return ast

    def _CSTR(self, ast):
        return ast

    def _EXPR(self, ast):
        return ast


def main(
        filename,
        startrule,
        trace=False,
        whitespace=None,
        nameguard=None,
        comments_re=None,
        eol_comments_re=None,
        ignorecase=None,
        left_recursion=True,
        **kwargs):

    with open(filename) as f:
        text = f.read()
    parser = SSSLParser(parseinfo=False)
    ast = parser.parse(
        text,
        startrule,
        filename=filename,
        trace=trace,
        whitespace=whitespace,
        nameguard=nameguard,
        ignorecase=ignorecase,
        **kwargs)
    return ast

if __name__ == '__main__':
    import json
    ast = generic_main(main, SSSLParser, name='SSSL')
    print('AST:')
    print(ast)
    print()
    print('JSON:')
    print(json.dumps(ast, indent=2))
    print()
