(* __Main__ *)

START = {BLOCK+:DEFS}* $ ;
 
DEFS = DOBJT:DOBJT | DFUNC:DMAIN | DFUNC:DFUNC | DECLAFF:DECLAFF | DECLAFF:DECLAFF | DECL:DECL | AFF:AFF;



(* __Instructions__ *)

BLOCK = '{' @:EMPTY '}' | '{' ({@+:INSTR}+ | @:NULL) '}' ;

INSTR = @:COND | @:OTHER | CFUNC:CFUNC | @:DEFS ;

COND = IF:IF | ELSE:ELSE | ELIF:ELIF | WHILE:WHILE | DOWHILE:DOWHILE ;

DECL = TYPE:TYPE NAME:nom ;

DECLAFF = TYPE:TYPE NAME:nom '=' EXPR:EXPR ;

AFF = NAME:nom '=' EXPR:EXPR ;

CFUNC = NAME:nom ARGS:ARGS ;

OTHER = RETURN:RETURN | BREAK:BREAK ;

RETURN = 'return' EXPR:EXPR | 'return' @:EMPTY ;

BREAK = 'break' @:EMPTY ;



(* __Conditions__ *)

IF = 'if' '(' EXPR:EXPR ')' BLOCK:BLOCK ; 

ELSE = 'else' BLOCK:BLOCK ; 

ELIF = 'elif' '(' EXPR:EXPR ')' BLOCK:BLOCK ;

WHILE = 'while' '(' EXPR:EXPR ')' BLOCK:BLOCK ; 

DOWHILE = 'do' BLOCK:BLOCK 'while' '(' EXPR:EXPR ')' ;



(* __Paramètres Arguments__ *)

PARAM = '(' @:EMPTY ')' | '(' [@:_TYPE @:_nom {',' @:_TYPE @:_nom}*] ')' ;

ARGS = '(' @:EMPTY ')' | '(' [@+:_EXPR {',' @+:_EXPR}*] ')' ;

EMPTY = {} ;



(* __Objets Fonctions__ *)

DOBJT = 'class' NAME:nom '{' {BLOCK+:DMEMB}* '}' ;

DMEMB = DFUNC:DFUNC | DECLAFF:DECLAFF | DECL:DECL | CSTR:CSTR;

DFUNC = 'func' TYPE:TYPE NAME:nom PARAM:PARAM BLOCK:BLOCK ;

DMAIN = TYPE:TYPE NAME:'Main' PARAM:PARAM BLOCK:BLOCK ;

CSTR = NAME:nom PARAM:PARAM BLOCK:BLOCK ;



(* __Types Opérateurs__ *)

TYPE = @:nom ;

OPER = '.' | '+' | '-' | '*' | '/' | '==' | '!='  ;


(* __Expressions__ *)

_EXPR = EXPR:EXPR ;

EXPR = @:t_EXPR @:OPER @:EXPR | @:t_EXPR ;

t_EXPR = CFUNC:CFUNC | NAME:nom | VAL:val ;

nom = /[a-zA-Z_]+/ ;

tout =/[0-9a-zA-Z_]+/ ;

val = /[0-9]+/ ;



(* __Autres__ *)

NULL = @:() ;

_DFUNC = DFUNC:DFUNC ;

_DECLAFF = DECLAFF:DECLAFF ;

_DECL = DECL:DECL ;

_TYPE = TYPE:TYPE ;

_nom = NAME:nom ;

_CSTR = CSTR:CSTR ;

