
START = { INSTR } $ ;

INSTR = DECL~ | AFFECT ;

DECL = DECL:() TYPE:type NAME:nom '=' EXPR:expr ;						(* Instruction *)

AFFECT = AFFECT:() NAME:nom '=' EXPR:expr ;									(* Instruction *)

expr = t_expr '+' expr | t_expr ;

t_expr = object~ | f_nom~ | f_val ;	 	

object = CLASS_N:nom '(' ARGS:args ')' ;

args = EXPR:expr ',' EXPR:expr~ | EXPR:expr ;									(* | FUNC *)

(* ___ *)

type = ('int'~ | 'float') ;

nom = /[a-z]+/ ;

val = /[0-9]+/ ;

f_type = TYPE:type ;

f_nom = NAME:nom ;

f_val = VAL:val ;
